services:
  # Consumer 서비스 (metrics-backend/consumer)
  consumer:
    image: isslab/im-metrics-consumer
    container_name: consumer
    environment:
      - TZ=${TZ}
      - BOOTSTRAP_SERVER=${BOOTSTRAP_SERVER}
      - KAFKA_TOPIC_NAME=${KAFKA_TOPIC_NAME}
      - KAFKA_CONSUMER_GROUP_ID=${KAFKA_CONSUMER_GROUP_ID}
      - API_BASE_URL=${API_BASE_URL}
    networks:
      - monitoring_network
    restart: always

networks:
  monitoring_network:
    driver: bridge