services:
  data-collector:
    image: isslab/im-data-collector:latest  # 직접 빌드한 이미지로 변경
    container_name: data-collector
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - BOOTSTRAP_SERVER=${BOOTSTRAP_SERVER}
      - KAFKA_TOPIC_NAME=${KAFKA_TOPIC_NAME}
      - TZ=${TZ}
    ports:
      - "8001:8001"
    networks:
      - monitoring_network
    restart: always

networks:
  monitoring_network:
    driver: bridge
